---

  tasks:
  - name: start dhcpd
    service: name=dhcpd state=started

  - name: add service to rc.conf.local
    sudo: yes
    lineinfile:
      dest=/etc/rc.conf.local
      backup=yes
      line="dhcpd_flags="""
      regexp='^'
      state=present
      insertafter=EOF
      create=True
