---

  tasks:
  - name: start nsd
    service: name=nsd state=started

  - name: add service to rc.conf.local
    sudo: yes
    lineinfile:
      dest=/etc/rc.conf.local
      backup=yes
      line="nsd_flags="""
      regexp='^'
      state=present
      insertafter=EOF
      create=True
