---

  tasks:
  - name: start ntpd
    service: name=ntpd state=started

  - name: add service to rc.conf.local
    sudo: yes
    lineinfile:
      dest=/etc/rc.conf.local
      backup=yes
      line="ntpd_flags="-s""
      regexp='^'
      state=present
      insertafter=EOF
      create=True

  - name: set time
    sudo: yes
    shell: ntpd -s -d
