---

  tasks:

  - name: adjust installpath in /etc/pkg.conf
    sudo: yes
    lineinfile:
      dest=/etc/pkg.conf
      backup=yes
      line="installpath = http://ftp.eu.openbsd.org/pub/OpenBSD/{{ release }}/packages/`machine -a`/"
      regexp='^'
      state=present
      insertafter=EOF
      create=True

  - name: install required packages
    sudo: yes
    openbsd_pkg: name={{ item }} state=present
    with_items:
      - fossil
      - igmpproxy
      - mc
      - nginx
      - radicale
      - rss2email
      - vim
      - unbound
