  tasks:
  - name: copy pf.conf
    action: copy src=files/pf.conf
      dest=/etc/pf.conf owner=root group=wheel mode=0644
    notify:
      - reload pf

  handlers:
    - name: reload pf
      action: shell /sbin/pfctl -f /etc/pf.conf
