---

  tasks:
  - name: start watchdog
    service: name=watchdog state=started

  - name: add service to rc.conf.local
    sudo: yes
    lineinfile:
      dest=/etc/rc.conf.local
      backup=yes
      line="watchdogd_flags="-i 3 -p 30""
      regexp='^'
      state=present
      insertafter=EOF
      create=True
