---

- hosts: workstation
  roles:
    - common
    - { role: workstation, when: is_workstation }

- hosts: gw
  roles:
    - common
    - { role: gw, when: is_gw }

- hosts: storage
  roles:
    - common
    - { role: storage, when: is_storage }

- hosts: cloud
  roles:
    - common
    - { role: libvirt_development, when: is_libvirt_development }
    - { role: openbsd_development, when: is_openbsd_development }
    - { role: openbsd_testing, when: is_openbsd_development }
