---
- hosts: all
  gather_facts: true
  user: sergeyb

  vars:
    pkg_path: "http://ftp.eu.openbsd.org/pub/OpenBSD/"
    github_user: "ligurio"
    kernel_params:
      - { name: kern.watchdog.auto, value: 1 }
      - { name: kern.watchdog.auto, value: 1 }
      - { name: kern.watchdog.period, value: 10 }
      - { name: kern.nosuidcoredump, value: 2 }
      - { name: ddb.panic, value: 1 }
      - { name: ddb.console, value: 1 }
      - { name: ddb.log, value: 1 }
      - { name: ddb.trigger, value: 1 }

  tasks:

  - name: ensure SSH keys are installed
    authorized_key: user=root key=https://github.com/{{ github_user }}.keys
    become_method: doas
    become: true

  - name: /etc/installurl
    lineinfile:
      dest=/etc/pkg.conf
      backup=yes
      line="{{ pkg_path }}"
      state=present
      create=True
    become_method: doas
    become: true

  - name: adjust sysctl parameters
    sysctl: name={{ item.name }} value={{ item.value }} state=present sysctl_file=/etc/sysctl.conf
    with_items: "{{ kernel_params }}"
    become_method: doas
    become: true

  - name: install packages
    openbsd_pkg: name={{ item }} state=present
    with_items:
        - py-test
        - py-pip
        - git
    become_method: doas
    become: true

  - name: checkout source code of regression tests
    git:
      repo: https://github.com/ligurio/openbsd-tests
      dest: /home/regress/openbsd-tests
      accept_hostkey: yes
      clone: yes
      update: yes

  - name: disable cron(8)
    file: path=/etc/{{ item }} mode=0555
    with_items:
        - daily
        - weekly
        - monthly
    become_method: doas
    become: true

  - name: enable watchdogd service in the rc.conf.local
    lineinfile:
      dest=/etc/rc.conf.local
      backup=yes
      line="watchdogd_flags=\"-i 3 -p 30\""
      regexp='^'
      state=present
      insertafter=EOF
      create=True
    become_method: doas
    become: true

  - name: start watchdog
    service: name=watchdog state=started
    become_method: doas
    become: true
