---
- hosts: all
  gather_facts: false
  user: root

  vars:
    pkg_path: "http://ftp.eu.openbsd.org/pub/OpenBSD/"
    workstation_package_set:
      - ImageMagick
      - ansible
      - autocutsel
      - bmf--
      - bzip2
      - chromium
      - colorls
      - curl
      - deadbeef
      - djview4
      - dmidecode
      - exiftran
      - exiv2
      - fdm
      - fdupes
      - feh
      - firefox
      - fossil--
      - gimp
      - git
      - gnuplot--no_x11
      - go
      - gpsbabel
      - gpsd
      - imapfilter
      - ispell
      - ispell-russian
      - jhead
      - josm
      - kismet
      - latex-mk
      - lbdb
      - lbdb-ldap
      - ledger
      - liberation-fonts
      - libreoffice
      - libreoffice-i18n-ru
      - lifelines
      - mpc
      - mpd
      - mplayer
      - msmtp
      - mutt--gpgme
      - ncmpc
      - ntfs_3g
      - offlineimap
      - openttd
      - p7zip
      - p7zip-rar
      - passwdqc
      - pianobar
      - pidgin--gtkspell
      - pjsua
      - polipo
      - pwsafe--no_x11
      - python
      - qgit
      - redshift
      - remmina
      - rss2email
      - rsync
      - rtunes
      - ru-ptsans
      - scrot
      - smartmontools
      - sox
      - sxiv
      - tango-icon-theme
      - tango-icon-theme-extras
      - terminus-font--
      - tesseract
      - tesseract-rus
      - texlive_base
      - texlive_texmf-minimal
      - tkabber
      - tkabber-plugins
      - tor
      - ubuntu-fonts
      - unpaper
      - unzip--iconv
      - urlview--
      - usbutils
      - vim
      - virt-viewer
      - wpa_supplicant
      - xbattbar
      - xbindkeys
      - xclip
      - xdg-utils
      - xmahjongg
      - xpdf
      - zathura
    gw_package_set:
      - fossil
      - igmpproxy
      - mc
      - radicale
      - rss2email
      - vim
    storage_package_set:
      - beets
      - flow-tools
      - fossil
      - mc
      - minidlna
      - munin
      - nginx
      - rsnapshot
      - seafile
      - transmission
      - vim
      - vsftpd

  tasks:
  - name: /etc/installurl
    lineinfile:
      dest=/etc/pkg.conf
      backup=yes
      line="{{ pkg_path }}"
      state=present
      create=True
    become_method: doas
    become: true

  - name: install packages
    openbsd_pkg: name={{ item }} state=present
    with_items: "{{ workstation_package_set }}"
    become_method: doas
    become: true
