---

# http://kb.mozillazine.org/Profile_folder_-_Firefox
# https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/Alternative_distribution_options/Sideloading_add-ons
# https://developer.mozilla.org/en-US/docs/Mozilla/Projects/NSS/tools/NSS_Tools_certutil

# TODO: setup firefox extensions
# TODO: import certificates
