# echo "sergeyb.qa.sw.ru" > hosts
# ansible-playbook -i hosts  -K openbsd.yml --extra-vars "hosts=sergeyb.qa.sw.ru user=sergeyb mirror=ftp.eu.openbsd.org"

---
- hosts: '{{ hosts }}'
  remote_user: '{{ user }}'
  gather_facts: no
  connection: ssh
  vars:
    mirror: ftp.eu.openbsd.org

  tasks:
  - name: adjust installpath in /etc/pkg.conf
    sudo: yes
    lineinfile:
      dest=/etc/pkg.conf
      backup=yes
      line="installpath = http://{{ mirror }}/pub/OpenBSD/`uname -r`/packages/`machine -a`/"
      regexp='^'
      state=present
      insertafter=EOF
      create=True

  - name: install required packages
    sudo: yes
    openbsd_pkg: name={{ item }} state=present
    with_items:
      - ImageMagick
      - abook
      - ansible
      - autocutsel
      - bmf
      - btpd
      - bzip2
      - chromium
      - colorls
      - curl
      - deadbeef
      - dictd-client
      - dictd-server
      - djview4
      - dmidecode
      - e2fsprogs
      - exiftran
      - exiv2
      - fdm
      - fdupes
      - feh
      - firefox
      - fossil
      - gimp
      - git
      - gnuplot
      - go
      - goldendict
      - gpsbabel
      - gpsd
      - imapfilter
      - ispell
      - ispell-russian
      - jhead
      - josm
      - jpegexiforient
      - kismet
      - latex-mk
      - lbdb
      - lbdb-ldap
      - ledger
      - liberation-fonts
      - libreoffice
      - libreoffice-i18n-ru
      - lifelines
      - lxrandr
      - mc
      - minidlna
      - minitube
      - mktorrent
      - mpc
      - mpd
      - mpg321
      - mplayer
      - msmtp
      - mutt
      - ncmpc
      - net-snmp
#      - notebook
      - ntfs-3g
#      - nvpy
      - offlineimap
      - openconnect
      - openct
      - openmdns
      - opensc
      - openttd
      - p7zip
      - p7zip-rar
      - passwdqc
      - pcsc-lite
      - pianobar
      - pidgin
      - pjsua
      - polipo
      - pptp
      - pwsafe
      - py-ldap
      - py-snmp
      - python
      - redshift
      - remmina
      - reop
      - rss2email
      - rsync
      - rtunes
      - ru-ptsans
      - ruby
      - scrot
      - smartmontools
      - sox
      - sxiv
      - tango-icon-theme
      - tango-icon-theme-extras
      - terminus-font
      - tesseract
      - tesseract-rus
      - texlive_base
      - texlive_texmf-minimal
      - tkabber
      - tkabber-plugins
      - tor
      - ubuntu-fonts
      - unpaper
      - unzip
      - urlview
      - usbutils
      - vim
      - virt-viewer
      - wpa_supplicant
      - xbattbar
      - xbindkeys
      - xclip
      - xdg-utils
      - xmahjongg
      - xpdf
      - xsel
